title: Nayab Basha Sayed | Embedded Systems Developer
description: > # this means to ignore newlines until "baseurl:"
    Embedded Systems developer, blogger and Linux enthusiast. This blog includes posts related to Linux and Embedded Systems.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nayab.xyz" # the base hostname & protocol for your site, e.g. http://example.com
permalink: none

excerpt_separator: <!--more-->
imgbase: /assets/img/
email: basha@nayab.xyz
author: "Nayab Basha Sayed"

#Google Analytics
google_analytics: UA-47925331-9
google_adsense: true

#Limit no of posts to parse and publish
#limit_posts: 10

logo: /favicon.ico
facebook_url: https://facebook.com/itsnayabsd
twitter_url: https://twitter.com/itsnayabsd
linkedin_url: https://www.linkedin.com/in/nayabsd/
pinterest_url:  
instagram_url: https://www.instagram.com/itsnayabsd/

# Build settings
markdown: kramdown

gems:
  - jekyll-toc
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

exclude:
    #- Gemfile
    #- Gemfile.lock
toc:
    min_level: 2
    max_level: 2
twitter:
    card: summary
    username: itsnayabsd

facebook:
    publisher: https://www.facebook.com/itsnayabsd

social:
    name: Nayab Basha Sayed
    links:
        - https://facebook.com/itsnayabsd
        - https://twitter.com/itsnayabsd
        - https://www.linkedin.com/in/nayabsd/
        - https://github.com/nayabbashasayed
        - https://www.instagram.com/itsnayabsd

lang: en
feed:
    path: atom.xml
sass:
  style: compressed
compress_html:
  clippings: all
  comments: [""]
  endings: [html, head, body, li, dt, dd, rt, rp, optgroup, option, colgroup, caption, thead, tbody, tfoot, tr, td, th]
  profile: false
  blanklines: false
  ignore:
    envs: []
