title: Nayab Basha Sayed | Embedded Software Engineer
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
    This is my personal website. I've been working as an embedded systems software engineer. I write blog posts about embedded system technologies. This website is also like like my personal notes about topics what I learned and what I've been learning. - Nayab Basha Sayed
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.nayab.xyz" # the base hostname & protocol for your site, e.g. http://example.com
permalink: none

excerpt_separator: <!--more-->
imgbase: /assets/img/
email: basha@naybas.org

#twitter_username: jekyllrb
#github_username:  jekyll

#Google Analytics
google_analytics: UA-47925331-9
google_adsense: false

#Limit no of posts to parse and publish
#limit_posts: 10

# Build settings
markdown: kramdown
#theme: minima
gems:
    #    - jekyll-feed
exclude:
    #- Gemfile
    #- Gemfile.lock
